<?php

namespace App\Support;

final class CuratedDemoCatalog
{
    public static function tracks(): array
    {
        return [
            [
                'slug' => 'seo-ai-max',
                'name' => 'SEO & AI',
                'description' => 'Lộ trình SEO thực chiến kết hợp dữ liệu, kỹ thuật và AI để tăng trưởng organic bền vững.',
                'titles' => [
                    'SEO Foundation: Xây nền tảng tăng trưởng bền vững',
                    'Nghiên cứu từ khóa theo Search Intent',
                    'Technical SEO Audit thực chiến',
                    'SEO Onpage cho website doanh nghiệp',
                    'Xây dựng Topic Cluster và Topical Authority',
                    'Ứng dụng AI trong quy trình SEO',
                    'Phân tích đối thủ và Content Gap',
                    'Đo lường SEO với Google Search Console',
                    'SEO cho website thương mại điện tử',
                    'Local SEO cho doanh nghiệp địa phương',
                    'Tối ưu Core Web Vitals cho SEO',
                    'Entity SEO và Semantic Search',
                    'Lập kế hoạch SEO 90 ngày',
                    'Xây dựng hệ thống Internal Link',
                    'SEO Migration không mất thứ hạng',
                    'Phân tích Log File cho Technical SEO',
                    'Keyword Mapping cho cấu trúc website',
                    'SEO Content Brief bằng dữ liệu',
                    'Tối ưu CTR trên trang kết quả tìm kiếm',
                    'SEO YouTube cho thương hiệu',
                    'Tự động hóa báo cáo SEO với Looker Studio',
                    'AI Prompting cho chuyên viên SEO',
                    'Phát hiện và xử lý Keyword Cannibalization',
                    'Tối ưu Crawl Budget cho website lớn',
                    'Schema Markup từ cơ bản đến nâng cao',
                    'Link Building an toàn và bền vững',
                    'SEO cho trang sản phẩm và danh mục',
                    'Phân tích nguyên nhân giảm traffic organic',
                    'Xây dựng Dashboard theo dõi SEO',
                    'Tối ưu Featured Snippet và People Also Ask',
                    'SEO Quốc tế với Hreflang',
                    'Quản trị dự án SEO cho đội ngũ Marketing',
                    'Content Pruning và phục hồi nội dung',
                    'Chiến lược SEO tích hợp AI Search',
                ],
            ],
            [
                'slug' => 'google-ads',
                'name' => 'Google Ads',
                'description' => 'Chương trình quảng cáo Google từ thiết lập, đo lường đến tối ưu hiệu quả kinh doanh.',
                'titles' => [
                    'Google Ads Search từ cơ bản đến tối ưu',
                    'Lập kế hoạch từ khóa cho quảng cáo tìm kiếm',
                    'Viết mẫu quảng cáo tăng tỷ lệ chuyển đổi',
                    'Performance Max cho doanh nghiệp',
                    'Tối ưu Landing Page cho Google Ads',
                    'Đo lường chuyển đổi với GA4 và GTM',
                    'Quản trị ngân sách và chiến lược đấu thầu',
                    'Phân tích báo cáo và tối ưu ROAS',
                    'Google Shopping cho thương mại điện tử',
                    'YouTube Ads xây dựng nhận diện thương hiệu',
                    'Display Ads và chiến lược Remarketing',
                    'Thiết lập tài khoản Google Ads chuẩn',
                    'Tối ưu Quality Score và Ad Rank',
                    'Broad Match và Smart Bidding thực chiến',
                    'Phân nhóm chiến dịch theo mục tiêu kinh doanh',
                    'Theo dõi cuộc gọi và Lead Form Conversion',
                    'Google Ads cho doanh nghiệp B2B',
                    'Google Ads cho ngành dịch vụ',
                    'Google Ads cho bán lẻ đa kênh',
                    'Phân tích Search Terms và Negative Keywords',
                    'Tối ưu chiến dịch khi ngân sách giới hạn',
                    'A/B Testing thông điệp quảng cáo',
                    'Ứng dụng AI để tối ưu Google Ads',
                    'Demand Gen Campaign thực chiến',
                    'Merchant Center và Product Feed chuẩn hóa',
                    'Giám sát Click Fraud và traffic kém chất lượng',
                    'Attribution trong Google Ads và GA4',
                    'Xây dựng Dashboard hiệu suất quảng cáo',
                    'Lập kế hoạch Media cho chiến dịch ra mắt',
                    'Tối ưu quảng cáo theo Customer Lifetime Value',
                    'Quản trị tài khoản Google Ads quy mô lớn',
                    'Audit Google Ads theo checklist chuyên sâu',
                    'Chiến lược tăng trưởng Paid Search bền vững',
                ],
            ],
            [
                'slug' => 'content-seo',
                'name' => 'Content Marketing',
                'description' => 'Hệ thống kỹ năng nghiên cứu, sáng tạo và phân phối nội dung gắn với hành trình khách hàng.',
                'titles' => [
                    'Content Marketing Foundation',
                    'Xây dựng chân dung khách hàng mục tiêu',
                    'Lập Content Plan theo hành trình khách hàng',
                    'Viết Content chuẩn SEO và dễ đọc',
                    'Copywriting cho Landing Page',
                    'Storytelling cho thương hiệu',
                    'Content Audit và tối ưu nội dung cũ',
                    'Xây dựng hệ thống Content đa kênh',
                    'Nghiên cứu Insight khách hàng bằng dữ liệu',
                    'Xây dựng Brand Voice nhất quán',
                    'Social Content cho Facebook và Instagram',
                    'TikTok Content Strategy cho doanh nghiệp',
                    'Email Marketing nuôi dưỡng khách hàng',
                    'Viết tiêu đề thu hút nhưng không giật gân',
                    'Content Brief cho đội ngũ và Agency',
                    'Biên tập nội dung chuyên nghiệp',
                    'Content Pillar cho chiến lược dài hạn',
                    'Video Script cho nội dung ngắn',
                    'Case Study thuyết phục khách hàng B2B',
                    'Content cho trang sản phẩm thương mại điện tử',
                    'Xây dựng Newsletter có giá trị',
                    'Repurpose Content trên nhiều nền tảng',
                    'Đo lường hiệu quả Content Marketing',
                    'Ứng dụng AI trong sáng tạo nội dung',
                    'Content Governance cho đội ngũ Marketing',
                    'Crisis Communication trên mạng xã hội',
                    'Community Content và xây dựng tương tác',
                    'Content Personalization theo phân khúc',
                    'Thought Leadership cho chuyên gia và lãnh đạo',
                    'Podcast Content từ ý tưởng đến phát hành',
                    'User Generated Content cho thương hiệu',
                    'Xây dựng Content Calendar vận hành hiệu quả',
                    'Chiến lược nội dung tăng trưởng bền vững',
                ],
            ],
        ];
    }

    public static function lessons(string $title): array
    {
        return [
            "Nền tảng và mục tiêu của {$title}",
            "Quy trình triển khai {$title}",
            "Phân tích dữ liệu và tối ưu kết quả",
            "Bài tập ứng dụng vào dự án thực tế",
        ];
    }
}
