import { FormEvent, useEffect, useState } from 'react';
import { Alert, Box, Button, Card, CardContent, Chip, Container, Divider, FormControl, InputLabel, MenuItem, Select, Stack, Tab, Tabs, TextField, Typography } from '@mui/material';
import { api, ApiError } from '../lib/api';
import type { ApiCategory, ApiCourse, ApiReview, ApiUser } from '../lib/contracts';
import { useAuth } from '../contexts/AuthContext';

type Stats = { students: number; courses: number; published_courses: number; enrollments: number; certificates: number; completion_rate: number; revenue: number };
const blankCourse = { title: '', description: '', thumbnail: '', price: '0', instructor_name: '', instructor_bio: '', level: 'beginner', status: 'draft' };

export function AdminPage() {
  const { token } = useAuth();
  const [tab, setTab] = useState('overview');
  const [stats, setStats] = useState<Stats | null>(null);
  const [users, setUsers] = useState<ApiUser[]>([]);
  const [categories, setCategories] = useState<ApiCategory[]>([]);
  const [courses, setCourses] = useState<ApiCourse[]>([]);
  const [reviews, setReviews] = useState<ApiReview[]>([]);
  const [categoryName, setCategoryName] = useState('');
  const [categoryDescription, setCategoryDescription] = useState('');
  const [courseForm, setCourseForm] = useState(blankCourse);
  const [courseCategoryId, setCourseCategoryId] = useState('');
  const [selectedCourse, setSelectedCourse] = useState<ApiCourse | null>(null);
  const [lessonTitle, setLessonTitle] = useState('');
  const [lessonUrl, setLessonUrl] = useState('');
  const [quizTitle, setQuizTitle] = useState('Bài kiểm tra cuối khóa');
  const [quizId, setQuizId] = useState<number | null>(null);
  const [questionContent, setQuestionContent] = useState('');
  const [correctOption, setCorrectOption] = useState('');
  const [wrongOption, setWrongOption] = useState('');
  const [notice, setNotice] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const reportError = (reason: unknown) => setError(reason instanceof ApiError ? reason.message : 'Không thể hoàn tất yêu cầu quản trị.');
  const load = async () => {
    if (!token) return;
    const [statResponse, userResponse, categoryResponse, courseResponse, reviewResponse] = await Promise.all([api.adminStats(token), api.adminUsers(token), api.adminCategories(token), api.adminCourses(token), api.adminReviews(token)]);
    setStats(statResponse); setUsers(userResponse.data); setCategories(categoryResponse.data); setCourses(courseResponse.data); setReviews(reviewResponse.data);
  };
  useEffect(() => { load().catch(reportError); }, [token]);
  const mutate = async (work: () => Promise<unknown>, successMessage: string) => { setError(null); try { await work(); setNotice(successMessage); await load(); } catch (reason) { reportError(reason); } };
  const createCategory = (event: FormEvent) => { event.preventDefault(); if (!token) return; void mutate(() => api.createCategory(token, { name: categoryName, description: categoryDescription || undefined }), 'Đã tạo danh mục.').then(() => { setCategoryName(''); setCategoryDescription(''); }); };
  const createCourse = (event: FormEvent) => { event.preventDefault(); if (!token || !courseCategoryId) return; void mutate(() => api.saveCourse(token, { ...courseForm, category_id: Number(courseCategoryId), price: Number(courseForm.price) }), 'Đã lưu khóa học.').then(() => { setCourseForm(blankCourse); setCourseCategoryId(''); }); };
  const addLesson = (event: FormEvent) => { event.preventDefault(); if (!token || !selectedCourse) return; void mutate(() => api.saveLesson(token, { title: lessonTitle, video_url: lessonUrl, duration: 0 }, selectedCourse.id), 'Đã thêm bài học.').then(() => { setLessonTitle(''); setLessonUrl(''); }); };
  const saveQuiz = (event: FormEvent) => { event.preventDefault(); if (!token || !selectedCourse) return; void api.saveQuiz(token, selectedCourse.id, { title: quizTitle, pass_score: 75, max_attempts: 3 }).then((quiz) => { setQuizId(quiz.id); setNotice('Đã lưu cấu hình bài kiểm tra. Bạn có thể thêm câu hỏi ngay bên dưới.'); }).catch(reportError); };
  const addQuestion = (event: FormEvent) => { event.preventDefault(); if (!token || !quizId) return; void api.saveQuestion(token, quizId, { content: questionContent, options: [{ content: correctOption, is_correct: true }, { content: wrongOption, is_correct: false }] }).then(() => { setQuestionContent(''); setCorrectOption(''); setWrongOption(''); setNotice('Đã thêm câu hỏi.'); }).catch(reportError); };

  return <Box sx={{ py: { xs: 4, md: 6 }, bgcolor: '#f7fafb', minHeight: '70dvh' }}><Container maxWidth="lg"><Stack spacing={3}>
    <Box><Typography component="h1" variant="h3" fontWeight={800}>Quản trị SEONGON LMS</Typography><Typography color="text.secondary" sx={{ mt: 1 }}>Quản lý dữ liệu và theo dõi hoạt động học tập từ API thật.</Typography></Box>
    {notice && <Alert severity="success" onClose={() => setNotice(null)}>{notice}</Alert>}{error && <Alert severity="error" onClose={() => setError(null)}>{error}</Alert>}
    <Tabs value={tab} onChange={(_, next) => setTab(next)} variant="scrollable" allowScrollButtonsMobile><Tab value="overview" label="Tổng quan" /><Tab value="students" label="Học viên" /><Tab value="categories" label="Danh mục" /><Tab value="courses" label="Khóa học" /><Tab value="content" label="Nội dung học" /><Tab value="reviews" label="Đánh giá" /></Tabs>
    {tab === 'overview' && <Box sx={{ display: 'grid', gridTemplateColumns: { xs: 'repeat(2, 1fr)', md: 'repeat(4, 1fr)' }, gap: 2 }}>{[['Học viên', stats?.students ?? 0], ['Khóa học', stats?.courses ?? 0], ['Ghi danh', stats?.enrollments ?? 0], ['Doanh thu', `${Number(stats?.revenue ?? 0).toLocaleString('vi-VN')} đ`]].map(([label, value]) => <Card key={String(label)} sx={{ borderRadius: 3 }}><CardContent><Typography color="text.secondary" variant="body2">{label}</Typography><Typography variant="h5" fontWeight={800} color="primary.main" sx={{ mt: 1 }}>{value}</Typography></CardContent></Card>)}</Box>}
    {tab === 'students' && <Card sx={{ borderRadius: 3 }}><CardContent><Typography component="h2" variant="h6" fontWeight={800}>Tài khoản học viên</Typography><Stack divider={<Divider flexItem />} sx={{ mt: 2 }}>{users.map((user) => <Stack key={user.id} direction={{ xs: 'column', sm: 'row' }} alignItems={{ sm: 'center' }} spacing={1.5} sx={{ py: 1.5 }}><Box sx={{ flexGrow: 1 }}><Typography fontWeight={700}>{user.name}</Typography><Typography variant="body2" color="text.secondary">{user.email}</Typography></Box><Chip label={user.status === 'active' ? 'Đang hoạt động' : 'Đã khóa'} color={user.status === 'active' ? 'success' : 'default'} size="small" /><Button size="small" variant="outlined" onClick={() => token && void mutate(() => api.updateUserStatus(token, user.id, user.status === 'active' ? 'locked' : 'active'), 'Đã cập nhật trạng thái tài khoản.')}>{user.status === 'active' ? 'Khóa' : 'Kích hoạt'}</Button></Stack>)}</Stack></CardContent></Card>}
    {tab === 'categories' && <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'minmax(260px, .6fr) 1fr' }, gap: 3 }}><Card component="form" onSubmit={createCategory} sx={{ borderRadius: 3 }}><CardContent><Stack spacing={2}><Typography component="h2" variant="h6" fontWeight={800}>Tạo danh mục</Typography><TextField required label="Tên danh mục" value={categoryName} onChange={(event) => setCategoryName(event.target.value)} /><TextField label="Mô tả" multiline minRows={3} value={categoryDescription} onChange={(event) => setCategoryDescription(event.target.value)} /><Button type="submit" variant="contained">Lưu danh mục</Button></Stack></CardContent></Card><Card sx={{ borderRadius: 3 }}><CardContent><Typography component="h2" variant="h6" fontWeight={800}>Danh mục hiện có</Typography><Stack divider={<Divider flexItem />} sx={{ mt: 2 }}>{categories.map((category) => <Stack key={category.id} direction="row" spacing={2} alignItems="center" sx={{ py: 1 }}><Box sx={{ flexGrow: 1 }}><Typography fontWeight={700}>{category.name}</Typography><Typography variant="body2" color="text.secondary">{category.courses_count ?? 0} khóa học</Typography></Box><Button color="error" size="small" onClick={() => token && void mutate(() => api.deleteCategory(token, category.id), 'Đã xóa danh mục.')}>Xóa</Button></Stack>)}</Stack></CardContent></Card></Box>}
    {tab === 'courses' && <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', lg: 'minmax(320px, .8fr) 1.2fr' }, gap: 3 }}><Card component="form" onSubmit={createCourse} sx={{ borderRadius: 3 }}><CardContent><Stack spacing={2}><Typography component="h2" variant="h6" fontWeight={800}>Tạo khóa học</Typography><FormControl required><InputLabel id="admin-category">Danh mục</InputLabel><Select labelId="admin-category" label="Danh mục" value={courseCategoryId} onChange={(event) => setCourseCategoryId(event.target.value)}>{categories.map((category) => <MenuItem key={category.id} value={String(category.id)}>{category.name}</MenuItem>)}</Select></FormControl><TextField required label="Tiêu đề" value={courseForm.title} onChange={(event) => setCourseForm({ ...courseForm, title: event.target.value })} /><TextField label="Mô tả" multiline minRows={3} value={courseForm.description} onChange={(event) => setCourseForm({ ...courseForm, description: event.target.value })} /><TextField required label="Giá" type="number" value={courseForm.price} onChange={(event) => setCourseForm({ ...courseForm, price: event.target.value })} /><TextField label="Tên giảng viên" value={courseForm.instructor_name} onChange={(event) => setCourseForm({ ...courseForm, instructor_name: event.target.value })} /><FormControl><InputLabel id="course-status">Trạng thái</InputLabel><Select labelId="course-status" label="Trạng thái" value={courseForm.status} onChange={(event) => setCourseForm({ ...courseForm, status: event.target.value })}><MenuItem value="draft">Bản nháp</MenuItem><MenuItem value="published">Xuất bản</MenuItem></Select></FormControl><Button type="submit" variant="contained">Lưu khóa học</Button></Stack></CardContent></Card><Card sx={{ borderRadius: 3 }}><CardContent><Typography component="h2" variant="h6" fontWeight={800}>Danh sách khóa học</Typography><Stack divider={<Divider flexItem />} sx={{ mt: 2 }}>{courses.map((course) => <Stack key={course.id} direction={{ xs: 'column', sm: 'row' }} spacing={1} alignItems={{ sm: 'center' }} sx={{ py: 1.5 }}><Box sx={{ flexGrow: 1 }}><Typography fontWeight={700}>{course.title}</Typography><Typography variant="body2" color="text.secondary">{course.status === 'published' ? 'Đang xuất bản' : 'Bản nháp'} · {Number(course.price).toLocaleString('vi-VN')} đ</Typography></Box><Button size="small" onClick={() => setSelectedCourse(course)}>Nội dung</Button><Button size="small" variant="outlined" onClick={() => token && void mutate(() => api.publishCourse(token, course.id, course.status === 'published' ? 'draft' : 'published'), 'Đã cập nhật trạng thái xuất bản.')}>{course.status === 'published' ? 'Ẩn' : 'Xuất bản'}</Button><Button size="small" color="error" onClick={() => token && void mutate(() => api.deleteCourse(token, course.id), 'Đã xóa khóa học.')}>Xóa</Button></Stack>)}</Stack></CardContent></Card></Box>}
    {tab === 'content' && <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', lg: 'minmax(270px, .6fr) 1fr' }, gap: 3 }}><Card sx={{ borderRadius: 3 }}><CardContent><Typography component="h2" variant="h6" fontWeight={800}>Chọn khóa học</Typography><Stack divider={<Divider flexItem />} sx={{ mt: 1 }}>{courses.map((course) => <Button key={course.id} onClick={() => { setSelectedCourse(course); setQuizId(null); }} color="inherit" sx={{ justifyContent: 'flex-start', textAlign: 'left', py: 1.5, fontWeight: selectedCourse?.id === course.id ? 800 : 400 }}>{course.title}</Button>)}</Stack></CardContent></Card><Stack spacing={3}>{!selectedCourse ? <Alert severity="info">Chọn một khóa học để thêm bài học và bài kiểm tra.</Alert> : <><Card component="form" onSubmit={addLesson} sx={{ borderRadius: 3 }}><CardContent><Stack spacing={2}><Typography component="h2" variant="h6" fontWeight={800}>Thêm bài học cho {selectedCourse.title}</Typography><TextField required label="Tiêu đề bài học" value={lessonTitle} onChange={(event) => setLessonTitle(event.target.value)} /><TextField required label="Video embed URL" value={lessonUrl} onChange={(event) => setLessonUrl(event.target.value)} /><Button type="submit" variant="contained">Thêm bài học</Button></Stack></CardContent></Card><Card component="form" onSubmit={saveQuiz} sx={{ borderRadius: 3 }}><CardContent><Stack spacing={2}><Typography component="h2" variant="h6" fontWeight={800}>Bài kiểm tra cuối khóa</Typography><TextField required label="Tiêu đề bài kiểm tra" value={quizTitle} onChange={(event) => setQuizTitle(event.target.value)} /><Button type="submit" variant="outlined">Lưu bài kiểm tra</Button></Stack></CardContent></Card>{quizId && <Card component="form" onSubmit={addQuestion} sx={{ borderRadius: 3 }}><CardContent><Stack spacing={2}><Typography component="h2" variant="h6" fontWeight={800}>Thêm câu hỏi</Typography><TextField required label="Câu hỏi" value={questionContent} onChange={(event) => setQuestionContent(event.target.value)} /><TextField required label="Đáp án đúng" value={correctOption} onChange={(event) => setCorrectOption(event.target.value)} /><TextField required label="Đáp án sai" value={wrongOption} onChange={(event) => setWrongOption(event.target.value)} /><Button type="submit" variant="contained">Thêm câu hỏi</Button></Stack></CardContent></Card>}</>}</Stack></Box>}
    {tab === 'reviews' && <Card sx={{ borderRadius: 3 }}><CardContent><Typography component="h2" variant="h6" fontWeight={800}>Duyệt đánh giá</Typography><Stack divider={<Divider flexItem />} sx={{ mt: 2 }}>{reviews.map((review) => <Stack key={review.id} direction={{ xs: 'column', sm: 'row' }} spacing={1.5} alignItems={{ sm: 'center' }} sx={{ py: 1.5 }}><Box sx={{ flexGrow: 1 }}><Typography fontWeight={700}>{review.user.name} · {review.rating}/5</Typography><Typography variant="body2" color="text.secondary">{review.comment || 'Không có nhận xét'}</Typography></Box><Chip size="small" label={review.status === 'visible' ? 'Hiển thị' : 'Đã ẩn'} /><Button size="small" variant="outlined" onClick={() => token && void mutate(() => api.updateReviewStatus(token, review.id, review.status === 'visible' ? 'hidden' : 'visible'), 'Đã cập nhật trạng thái đánh giá.')}>{review.status === 'visible' ? 'Ẩn' : 'Hiện'}</Button><Button size="small" color="error" onClick={() => token && void mutate(() => api.deleteReview(token, review.id), 'Đã xóa đánh giá.')}>Xóa</Button></Stack>)}</Stack></CardContent></Card>}
  </Stack></Container></Box>;
}
